trainer: forces

dataset:
    - src: /global/cfs/cdirs/m1759/catalysis_dl/oc20_data/s2ef/2M/train
      normalize_labels: True
      target_mean: -0.7554450631141663
      target_std: 2.887317180633545
      grad_target_mean: 0.0
      grad_target_std: 2.887317180633545
    - src: /global/cfs/cdirs/m1759/catalysis_dl/oc20_data/s2ef/all/val_id
    #- src: /global/cscratch1/sd/sfarrell/ocp/data/mlperf-testing/train
    #- src: /global/cscratch1/sd/sfarrell/ocp/data/mlperf-testing/val_id
    #- src: data/s2ef/200k/train/
    #- src: data/s2ef/all/val_id/

logger: wandb

task:
    dataset: trajectory_lmdb
    description: "Regressing to energies and forces for DFT trajectories from OCP"
    type: regression
    metric: mae
    primary_metric: forces_mae
    labels:
        - potential energy
    grad_input: atomic forces
    train_on_free_atoms: True
    eval_on_free_atoms: True

model:
    name: dimenetplusplus
    hidden_channels: 192
    out_emb_channels: 192
    num_blocks: 3
    cutoff: 6.0
    num_radial: 6
    num_spherical: 7
    num_before_skip: 1
    num_after_skip: 2
    num_output_layers: 3
    regress_forces: True
    use_pbc: True
    #otf_graph: True

optim:
    batch_size: 4 #2
    eval_batch_size: 4 #2
    #val_dist_sampler: True
    #eval_every: -1000
    num_workers: 4
    lr_initial: 0.0001
    lr_gamma: 0.1
    lr_milestones:
        - 128000 #4
        - 192000 #6
        - 256000 #8
    warmup_steps: 64000 #2
    #warmup_epochs: 2
    warmup_factor: 0.2
    max_epochs: 30
    energy_coefficient: 0
    force_coefficient: 50

slurm:
    partition: null
    constraint: gpu
    account: m1759
    qos: special
    time_min: "4:00:00"
